# -*- coding: utf-8 -*-
"""Interactive syntax/exam cheat-sheet. Every entry: syntax -> meaning -> example -> common mistake -> exam use."""

ENTRIES = [
    {
        "id": "let-binding", "title": "let binding", "category": "Basics",
        "syntax": "let name = expression",
        "meaning": "Binds an immutable value to an identifier. Not a variable assignment -- the name can never be rebound to a different value in the same scope.",
        "example": "```fsharp\nlet x = 5\nlet message = \"hello\"\n```",
        "common_mistake": "Treating it like `x = 5` in an imperative language and expecting to later mutate `x`.",
        "exam_use": "Every single F# program starts here -- used constantly to name intermediate results.",
    },
    {
        "id": "basic-types", "title": "Basic types", "category": "Basics",
        "syntax": "int, float, bool, string, char",
        "meaning": "F#'s primitive types. Type inference usually figures these out from literals, so annotations are often unnecessary.",
        "example": "```fsharp\nlet n = 5          // int\nlet f = 5.0        // float\nlet b = true        // bool\nlet s = \"hi\"       // string\nlet c = 'a'         // char\n```",
        "common_mistake": "Mixing int and float without converting (e.g. `1 + 0.5` is a compile error) -- must use `float 1 + 0.5`.",
        "exam_use": "Type mismatches are one of the most common reasons exam code fails to compile.",
    },
    {
        "id": "unit-type", "title": "unit type ()", "category": "Basics",
        "syntax": "()",
        "meaning": "F#'s \"nothing\" value, similar to `void`. Every function must return something, and every parameter must accept something, so a function with \"no result\" returns `unit`, and one with \"no input\" takes a single `()` argument.",
        "example": "```fsharp\nlet sayHi () =\n    printf \"hi\"\n    ()\n```",
        "common_mistake": "Forgetting an `if` without an `else` must have a `then` branch of type `unit` (since the implicit missing else is `()`).",
        "exam_use": "Comes up whenever a function's job is a side effect (printing) rather than computing a value.",
    },
    {
        "id": "match-expr", "title": "match ... with", "category": "Pattern Matching",
        "syntax": "match expr with\n| pattern1 -> result1\n| pattern2 when cond -> result2\n| _ -> resultDefault",
        "meaning": "Selects one expression from several options by matching `expr` against patterns in order, top to bottom. Every branch must produce the same type.",
        "example": "```fsharp\nlet toWord n =\n    match n with\n    | 1 -> \"one\"\n    | 2 -> \"two\"\n    | _ -> \"other\"\n```",
        "common_mistake": "Assuming it 'falls through' like a switch statement without a break -- only one branch ever executes.",
        "exam_use": "Used in almost every function in the module -- the default control-flow tool.",
    },
    {
        "id": "if-else-expr", "title": "if ... elif ... else", "category": "Pattern Matching",
        "syntax": "if cond1 then expr1\nelif cond2 then expr2\nelse expr3",
        "meaning": "An expression (not a statement) that evaluates to a value. Every branch must have the same type.",
        "example": "```fsharp\nlet abs x = if x >= 0 then x else -x\n```",
        "common_mistake": "Using `if` without `else` where a non-unit value is expected -- only legal when the `then` branch is `unit`.",
        "exam_use": "Interchangeable with `match` for simple boolean conditions; use whichever reads more clearly.",
    },
    {
        "id": "wildcard-pattern", "title": "Wildcard _ and identifier patterns", "category": "Pattern Matching",
        "syntax": "| _ -> ...      | someName -> ...",
        "meaning": "`_` matches anything and binds nothing. A bare identifier also matches anything, AND binds the matched value to that name for use on the right of `->`.",
        "example": "```fsharp\nmatch n with\n| 0 -> \"zero\"\n| n -> sprintf \"nonzero: %d\" n\n```",
        "common_mistake": "Putting `_` (or any catch-all identifier pattern) before more specific patterns -- later patterns become unreachable.",
        "exam_use": "Needed at the end of almost every non-exhaustive `match`.",
    },
    {
        "id": "rec-keyword", "title": "let rec", "category": "Recursion",
        "syntax": "let rec name params = ... name ...",
        "meaning": "Marks a function as recursive, allowing it to call itself within its own body.",
        "example": "```fsharp\nlet rec factorial k =\n    match k with\n    | 1 -> 1\n    | k -> k * factorial (k-1)\n```",
        "common_mistake": "Forgetting `rec` -- causes a compile error the moment the function refers to its own name.",
        "exam_use": "Required on essentially every list/tree/numeric processing function in this module.",
    },
    {
        "id": "tail-recursion", "title": "Tail recursion & accumulators", "category": "Recursion",
        "syntax": "let rec helper acc x = if base then acc else helper (newAcc) (smaller x)",
        "meaning": "A recursive call is the very last action performed, with nothing done to its result afterwards -- lets the compiler reuse the stack frame (O(1) stack space) instead of growing it (O(n)).",
        "example": "```fsharp\nlet sumTo n =\n    let rec go i acc = if i > n then acc else go (i+1) (acc+i)\n    go 1 0\n```",
        "common_mistake": "Calling something 'tail recursive' when an operator (like `::` or `+`) is still applied to the recursive call's result -- that's backward recursion, not tail recursion.",
        "exam_use": "Directly asked about in 'rewrite using forward/backward recursion' questions and efficiency-analysis questions.",
    },
    {
        "id": "list-append-op", "title": "@ (list append)", "category": "Lists",
        "syntax": "list1 @ list2",
        "meaning": "Concatenates two whole lists into one. O(n) in the length of the left-hand list.",
        "example": "```fsharp\nlet a = [1;2] @ [3;4]   // [1;2;3;4]\n```",
        "common_mistake": "Using `@` repeatedly inside a recursive accumulator (e.g. `ys @ [x]`) when `::` would be O(1) -- silently turns an O(n) algorithm into O(n^2).",
        "exam_use": "Central to every induction proof (Laws 3-6, 9, 10 all involve `@`) and to efficiency-analysis questions.",
    },
    {
        "id": "cons-operator", "title": ":: (cons operator)", "category": "Lists",
        "syntax": "element :: list",
        "meaning": "Attaches one element to the front of an existing list. O(1). Can be stacked: `a :: b :: rest`.",
        "example": "```fsharp\nlet x = 5 :: 2 :: 1 :: []   // [5;2;1]\n```",
        "common_mistake": "Writing `x :: 3` (element on both sides) instead of `x :: list` -- the right-hand side must be a list.",
        "exam_use": "The fundamental way to pattern-match and build lists throughout the entire module.",
    },
    {
        "id": "append-operator", "title": "List concatenation vs cons", "category": "Lists",
        "syntax": "h :: t   vs   list1 @ list2",
        "meaning": "`::` needs (element, list); `@` needs (list, list). Choosing the right one affects both correctness and efficiency.",
        "example": "```fsharp\nlet build x xs = x :: xs        // O(1), prefer this while recursing\nlet join a b = a @ b            // O(n), fine once, at the end\n```",
        "common_mistake": "Using `@` where `::` was possible, especially inside a recursive loop.",
        "exam_use": "Recursion Types topic and every 'analyse the efficiency of this function' question.",
    },
    {
        "id": "list-literal", "title": "List literals & ranges", "category": "Lists",
        "syntax": "[v1; v2; v3]     [start .. end]     [start .. step .. end]",
        "meaning": "Direct list syntax, and range syntax for sequential/stepped lists.",
        "example": "```fsharp\nlet a = [1;2;3]\nlet b = [1 .. 5]        // [1;2;3;4;5]\nlet c = [1 .. 2 .. 10]  // [1;3;5;7;9]\n```",
        "common_mistake": "Using commas instead of semicolons to separate list elements (`[1, 2, 3]` is a list containing one tuple, not three elements!).",
        "exam_use": "Used to quickly build test data for practical questions.",
    },
    {
        "id": "list-pattern-match", "title": "Pattern matching lists", "category": "Lists",
        "syntax": "match lis with\n| [] -> ...\n| (h::t) -> ...",
        "meaning": "`[]` matches only the empty list; `(h::t)` matches any list with at least one element, binding the head and tail.",
        "example": "```fsharp\nlet rec length lis =\n    match lis with\n    | [] -> 0\n    | (_::t) -> 1 + length t\n```",
        "common_mistake": "Forgetting the `[]` case, causing a MatchFailureException at runtime on empty input.",
        "exam_use": "The core technique for essentially every list-processing exam question.",
    },
    {
        "id": "lambda-expr", "title": "Anonymous functions (fun)", "category": "Higher-Order Functions",
        "syntax": "fun param -> expression",
        "meaning": "An inline, unnamed function value.",
        "example": "```fsharp\nlet double = fun x -> x * 2\nlist |> List.map (fun x -> x + 1)\n```",
        "common_mistake": "Writing `fun x -> x * x x` (double application by accident) instead of `x * x`.",
        "exam_use": "Common inside pipelines or as an argument to `List.map`/`List.filter`.",
    },
    {
        "id": "pipeline-operator", "title": "|> (pipeline operator)", "category": "Higher-Order Functions",
        "syntax": "value |> function",
        "meaning": "Passes `value` as the LAST argument to `function`. `x |> f y` desugars to `f y x`. Lets you write data transformations left-to-right.",
        "example": "```fsharp\nlet result = 5 |> square |> add1 |> toString\n```",
        "common_mistake": "Assuming the piped value becomes the FIRST argument -- it's always the last.",
        "exam_use": "Idiomatic style expected in higher-order-function questions; also appears directly in 'what does this pipeline evaluate to' trace questions.",
    },
    {
        "id": "composition-operators", "title": ">> and << (function composition)", "category": "Higher-Order Functions",
        "syntax": "f << g   (f after g, right-to-left)\nf >> g   (f then g, left-to-right)",
        "meaning": "Builds a new function by chaining two existing ones without naming an intermediate variable.",
        "example": "```fsharp\nlet fog = f << g     // fog x = f (g x)\nlet hgf = h >> g >> f // hgf x = f (g (h x))\n```",
        "common_mistake": "Mixing up which operator reads left-to-right (`>>`) vs right-to-left (`<<`, matches maths notation f∘g).",
        "exam_use": "Type-signature and 'trace the output' questions frequently test this directly.",
    },
    {
        "id": "currying", "title": "Currying & partial application", "category": "Higher-Order Functions",
        "syntax": "let f x y = ...   // really:  int -> (int -> int)\nlet g = f 5        // partially applied",
        "meaning": "Every 'multi-parameter' F# function is really a chain of one-parameter functions. Supplying fewer arguments than the full count produces a new function waiting for the rest.",
        "example": "```fsharp\nlet add a b = a + b\nlet add5 = add 5      // int -> int\nadd5 10                // 15\n```",
        "common_mistake": "Thinking `let f x y = ...` has 'two parameters' in the C/Java sense rather than one, returning a function.",
        "exam_use": "Frequently tested with 'what is the type of this expression' questions.",
    },
    {
        "id": "tuple-literal", "title": "Tuples", "category": "Data Structures",
        "syntax": "(v1, v2, ..., vn)     type: t1 * t2 * ... * tn",
        "meaning": "A fixed-size grouping of unnamed values where order matters. A single value even though it holds several things.",
        "example": "```fsharp\nlet pair = (5, \"hello\")   // int * string\nlet (a, b) = pair\n```",
        "common_mistake": "Confusing tuple type syntax (`int * string`) with multiplication.",
        "exam_use": "Very common as a way to 'return multiple values' from a function in one pass.",
    },
    {
        "id": "fst-snd", "title": "fst / snd", "category": "Data Structures",
        "syntax": "fst pair     snd pair",
        "meaning": "Built-in accessors for the first/second element of a 2-tuple (pair) only.",
        "example": "```fsharp\nlet p = (5, \"hi\")\nfst p   // 5\nsnd p   // \"hi\"\n```",
        "common_mistake": "Trying to use `fst`/`snd` on a 3-tuple or larger -- they only exist for pairs; pattern-match instead.",
        "exam_use": "Common in tuple-returning recursive functions (e.g. sum-and-product accumulators).",
    },
    {
        "id": "record-type", "title": "Record types", "category": "Data Structures",
        "syntax": "type name = { field1 : type1; field2 : type2 }",
        "meaning": "A grouping of NAMED fields, accessed by name; order doesn't matter for construction.",
        "example": "```fsharp\ntype person = { name : string; age : int }\nlet p = { name = \"Sam\"; age = 21 }\n```",
        "common_mistake": "Trying to define a record type inline inside a function -- record types must be declared at module level.",
        "exam_use": "Its own dedicated exam section every year -- expect a record definition + list-of-records processing question.",
    },
    {
        "id": "record-update", "title": "Record update syntax { x with ... }", "category": "Data Structures",
        "syntax": "{ existingRecord with field = newValue }",
        "meaning": "Builds a NEW record, copying every field from `existingRecord` except the ones overridden after `with`. Does not mutate the original.",
        "example": "```fsharp\nlet p2 = { p with age = p.age + 1 }\n```",
        "common_mistake": "Thinking this mutates `p` in place -- `p` is unchanged; `p2` is a distinct new value.",
        "exam_use": "Used any time you need to 'update' a field of a record in a list of records (e.g. updating rank/score fields).",
    },
    {
        "id": "generics", "title": "Generics ('a, 'b, ...)", "category": "Data Structures",
        "syntax": "let swap (a, b) = (b, a)   // inferred as: 'a * 'b -> 'b * 'a",
        "meaning": "A placeholder type parameter meaning 'works for any type here'. Usually inferred automatically; you rarely write `'a` explicitly.",
        "example": "```fsharp\nlet identity x = x   // 'a -> 'a\n```",
        "common_mistake": "Adding generics manually when they aren't needed -- if the code isn't ambiguous, let inference handle it.",
        "exam_use": "Mostly about recognising generic signatures when reading them, rather than writing `'a` yourself.",
    },
    {
        "id": "range-syntax", "title": "Range syntax", "category": "Lists",
        "syntax": "[start .. end]     [start .. step .. end]",
        "meaning": "Generates a list of sequential (or evenly stepped) values.",
        "example": "```fsharp\n[1 .. 5]        // [1;2;3;4;5]\n[10 .. -2 .. 0] // [10;8;6;4;2;0]\n```",
        "common_mistake": "Forgetting a negative step is required to count downward.",
        "exam_use": "Used to quickly generate test ranges inside comprehensions.",
    },
    {
        "id": "list-comprehension", "title": "List comprehensions", "category": "Lists",
        "syntax": "[ for x in range do yield expr ]\n[ for x in range do if cond then yield expr ]",
        "meaning": "Compact syntax for building a list by mapping (and optionally filtering) over a range or another list.",
        "example": "```fsharp\nlet squares = [ for x in 1 .. 5 do yield x * x ]\nlet evens = [ for x in 1 .. 20 do if x % 2 = 0 then yield x ]\n```",
        "common_mistake": "Forgetting `do` before `yield`, or misplacing the `if` (the condition guards whether to `yield`, it doesn't change the value being yielded unless you write that logic yourself).",
        "exam_use": "Often the cleanest way to answer 'without built-in functions' practical questions.",
    },
    {
        "id": "yield-bang", "title": "yield vs yield!", "category": "Lists",
        "syntax": "yield expr      // adds ONE element\nyield! subList  // splices in a WHOLE list",
        "meaning": "`yield` contributes a single value per iteration; `yield!` flattens an entire sub-list into the result instead of nesting it.",
        "example": "```fsharp\n[ for a in 1 .. 3 do yield! [a .. a+2] ]\n```",
        "common_mistake": "Using `yield` when the expression is itself a list, producing a nested list of lists instead of a flat list.",
        "exam_use": "Comes up in permutation-generation and other comprehension-heavy recursive functions.",
    },
    {
        "id": "list-module-fns", "title": "List module: map / filter / fold / reduce", "category": "Lists",
        "syntax": "List.map f lis\nList.filter f lis\nList.fold f initial lis\nList.reduce f lis",
        "meaning": "Ready-made higher-order functions: transform every element (map), keep elements matching a predicate (filter), combine all elements into one value from a starting point (fold), or the same without a separate starting value (reduce, needs a non-empty list).",
        "example": "```fsharp\nList.map (fun x -> x*2) [1;2;3]     // [2;4;6]\nList.filter (fun x -> x>1) [1;2;3]  // [2;3]\nList.fold (+) 0 [1;2;3]              // 6\n```",
        "common_mistake": "Using `List.reduce` on a possibly-empty list -- it throws; `List.fold` with an explicit initial value is safer.",
        "exam_use": "Often explicitly BANNED ('do not use built-in functions') to force you to hand-write the recursive equivalent -- always check the question's instructions.",
    },
    {
        "id": "induction-laws", "title": "The 10 list Laws (induction axioms)", "category": "Proofs",
        "syntax": "See full list on the Structural Induction topic page.",
        "meaning": "A fixed set of identities about lists (about `::`, `@`, `head`/`tail`, `length`, `reverse`, `take`/`drop`) that you're allowed to cite as justification in an induction proof.",
        "example": "```\nLaw 6: (x::xs) @ ys = x :: (xs @ ys)\n```",
        "common_mistake": "Trying to unfold `(x::xs) @ ys` directly with the function's own recursive definition without first applying Law 6.",
        "exam_use": "Provided in an appendix on every exam paper -- memorising them isn't required, but fluently recognising WHEN to apply each one is essential.",
    },
    {
        "id": "lambda-syntax", "title": "Lambda calculus expression syntax", "category": "Lambda Calculus",
        "syntax": "<name>            e.g. x\n\\<name>.<expr>    a function, e.g. \\x.x\n(<function> <expr>)  an application, e.g. (\\x.x y)",
        "meaning": "The three forms every lambda calculus expression is built from -- a name, a function (lambda abstraction), or an application of a function to an argument.",
        "example": "```\n\\f.\\x.(f x)\n```",
        "common_mistake": "Dropping the parentheses around an application, or misplacing the `.` after the bound name.",
        "exam_use": "Appears in every exam's Theory section.",
    },
    {
        "id": "beta-reduction", "title": "Beta reduction", "category": "Lambda Calculus",
        "syntax": "(\\v.body  arg)  ->  body[v := arg]",
        "meaning": "The single computation rule of lambda calculus: substitute every occurrence of the bound variable in the body with the argument. This course reduces leftmost-outermost first.",
        "example": "```\n(\\x.x  \\y.y)  ->  \\y.y\n```",
        "common_mistake": "Reducing an inner redex before an available outer one -- breaks from the course's expected leftmost-outermost working.",
        "exam_use": "The mechanical skill tested by every 'evaluate this lambda expression' question.",
    },
    {
        "id": "church-booleans", "title": "Church-encoded booleans & logic", "category": "Lambda Calculus",
        "syntax": "True = \\a.\\b.a    False = \\c.\\d.d\nAnd = \\i.\\j.((i j) False)   Or = \\k.\\m.((k True) m)   Not = \\h.((h False) True)",
        "meaning": "Booleans and logical operators encoded purely as functions that pick one of two arguments.",
        "example": "```\n((And True) False)  reduces to False\n```",
        "common_mistake": "Forgetting these names are themselves lambda expressions that must be expanded/substituted before reducing further.",
        "exam_use": "Always provided in the exam appendix; used to build and evaluate expressions for given truth tables.",
    },
    {
        "id": "discriminated-union-syntax", "title": "Discriminated union declaration", "category": "Discriminated Unions",
        "syntax": "type name =\n    | Case1\n    | Case2 of dataType\n    | Case3 of type1 * type2",
        "meaning": "Declares a fixed, exhaustive set of mutually-exclusive alternatives ('OR' type), each optionally carrying data.",
        "example": "```fsharp\ntype shape =\n    | Circle of float\n    | Rectangle of float * float\n```",
        "common_mistake": "Forgetting a case in a later `match`, especially after adding a new case mid-question.",
        "exam_use": "The basis of the exam's largest practical section every year (trees, tries, custom data structures).",
    },
    {
        "id": "option-type", "title": "Option<'T>", "category": "Discriminated Unions",
        "syntax": "Some value     None",
        "meaning": "A built-in discriminated union representing 'a value that may or may not exist', avoiding null-reference-style errors.",
        "example": "```fsharp\nlet tryHead lis = match lis with | [] -> None | (h::_) -> Some h\n```",
        "common_mistake": "Using an `Option<'T>` value as if it directly were a `'T` -- must pattern-match (`Some x` / `None`) first.",
        "exam_use": "Used for 'may not exist' results in more advanced practical questions.",
    },
    {
        "id": "result-type", "title": "Result<'T,'E>", "category": "Discriminated Unions",
        "syntax": "Ok value     Error errValue",
        "meaning": "A built-in discriminated union representing 'an operation that succeeded with a value, or failed with an error'.",
        "example": "```fsharp\nlet safeDiv a b = if b = 0 then Error \"div by zero\" else Ok (a / b)\n```",
        "common_mistake": "Forgetting to pattern-match both `Ok` and `Error` cases.",
        "exam_use": "Less common than Option in this module's material, but conceptually paired with it.",
    },
    {
        "id": "tree-pattern-match", "title": "Pattern matching trees", "category": "Trees",
        "syntax": "match t with\n| Empty -> ...\n| Node (l, v, r) -> ...",
        "meaning": "Destructures a tree discriminated union into its sub-trees and value, exactly like matching lists into head/tail.",
        "example": "```fsharp\nlet rec height t =\n    match t with\n    | Empty -> 0\n    | Node (l, _, r) -> 1 + max (height l) (height r)\n```",
        "common_mistake": "Forgetting a tree traversal combining two recursive calls (left AND right) is not tail recursive -- that's expected and fine, just don't claim otherwise in an efficiency discussion.",
        "exam_use": "Core technique for the Discriminated Unions / Trees exam section every year.",
    },
]


def get_syntax_entries():
    return ENTRIES
